spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person?createDatabaseIfNotExist=true
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    database: MYSQL
    show-sql: true
    hibernate: 
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
server:
  port: 9080